version: "3.5"

services:
  client:
    container_name: client
    build:
      context: client
      target: production
    ports:
      - 80:80
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15.3
    restart: always
    container_name: db
    env_file:
      - ./server/.env

    ports:
      - 5432:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    networks:
      - app-network

  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     DOMAINS: "project-management.duckdns.org -> http://client:3000, api.project-management.duckdns.org -> http://server:8000"
  #     STAGE: "production" # Don't use production until staging works
  #     WEBSOCKET: "true"
  #   volumes:
  #     - https-portal-data:/var/lib/https-portal
  #   networks:
  #     - app-network

# volumes:
#   https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
networks:
  app-network:
