version: "3.5"

services:
  client:
    restart: always
    container_name: client
    build:
      context: client
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    container_name: server
    restart: always
    depends_on:
      - db
    build:
      context: server
    ports:
      - 8000:8000
    command: "npm run dev"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15.3
    restart: always
    env_file:
      - ./server/.env
    container_name: db

    ports:
      - 5432:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
